config/routes.rb
include LoaMatch
include AbTestConstraint

Rails.application.routes.draw do

  def add_routes(routes_name)
    instance_eval(File.read(Rails.root.join("config/#{routes_name}.rb")))
  end

  get "initiate-journey/:transaction_simple_id", to: "initiate_journey#index", as: :initiate_journey
  post "SAML2/SSO" => "authn_request#rp_request"
  post "SAML2/SSO/Response/POST" => "authn_response#idp_response"
  match "/404", to: "errors#page_not_found", via: :all

  if %w(test development).include?(Rails.env) || STUB_MODE
    mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
    get "test-saml" => "test_saml#index"
    get "/" => "test_saml#index"
    post "/" => "test_saml#index"
    post "test-rp", to: proc { |_| [200, {}, ["OK"]] }
    post "test-idp-request-endpoint" => "test_saml#idp_request"
    post "test-initiate-journey" => "test_saml#initiate_journey_session"
    get "test-session-expiry" => "test_saml#test_expiry"
    post "another-idp-endpoint" => "test_saml#idp_request"
    get "test-journey-hint" => "test_journey_hint_cookie#index", as: :test_journey_hint
    get "test-throttling-cookie/:idp" => "test_throttling_cookie#set_cookie"
    post "test-journey-hint" => "test_journey_hint_cookie#set_cookie", as: :test_journey_hint_submit
    get "test-single-idp-journey" => "test_single_idp_journey#index"
    get "analytics", to: "test_analytics#forward"
    post "csp-reporter", to: "test_csp_reporter#report"
  end

  constraints(format: /html/) do
    localized do
      add_routes :main_routes
    end
  end

  put "select-idp", to: "sign_in#select_idp_ajax", as: :select_idp_submit_ajax
  put "select-idp-for-registration", to: "choose_a_certified_company#select_idp_ajax", as: :select_idp_for_registration_ajax
  put "resume-with-idp", to: "paused_registration#resume_with_idp_ajax", as: :resume_with_idp_ajax
  get "service-status", to: "service_status#index", as: :service_status
  get "hint", to: "hint#ajax_request"
  get "successful-idp", to: "hint#last_successful_idp"
  get "/SAML2/metadata/sp", to: "metadata#service_providers", as: :service_provider_metadata
  get "/SAML2/metadata/idp", to: "metadata#identity_providers", as: :identity_provider_metadata
  if SINGLE_IDP_FEATURE
    get "get-available-services", to: "metadata#service_list"
    post "initiate-single-idp-journey", to: "single_idp_journey#redirect_from_idp"
    put "select-single-idp", to: "single_idp_journey#continue_ajax"
  end
  if PUBLISH_HUB_CONFIG_ENABLED
    get "hub/config/service-status", to: "publish_hub_config#service_status"
    match "hub/config/config/certificates/:path", to: "publish_hub_config#certificates", constraints: { path: /.*/ }, via: :get
  end
  get "/humans.txt", to: "static#humanstxt"
end

app/views/may_not_work_if_you_live_overseas/index.html.erb
<% content_for :page_title, t('hub.may_not_work_if_you_live_overseas.title') %>
<% content_for :feedback_source, 'MAY_NOT_WORK_IF_YOU_LIVE_OVERSEAS_PAGE' %>

<div class="grid-row">
  <div class="column-two-thirds">
    <h1 class="heading-xlarge"><%= t 'hub.may_not_work_if_you_live_overseas.heading' %></h1>

    <p><%= t 'hub.may_not_work_if_you_live_overseas.explanation1' %></p>
    <p><%= t 'hub.may_not_work_if_you_live_overseas.explanation2' %></p>

    <h2 class="heading-medium"><%= t 'hub.may_not_work_if_you_live_overseas.what_youll_need' %></h2>

    <p><%= t 'hub.may_not_work_if_you_live_overseas.if_you_have_these' %>:</p>

    <ul class="list-bullet list">
      <li><%= t 'hub.may_not_work_if_you_live_overseas.current_account_overdraft' %></li>
      <li><%= t 'hub.may_not_work_if_you_live_overseas.credit_card' %></li>
      <li><%= t 'hub.may_not_work_if_you_live_overseas.phone_contract' %></li>
      <li><%= t 'hub.may_not_work_if_you_live_overseas.gas_electricity_bills' %></li>
      <li><%= t 'hub.may_not_work_if_you_live_overseas.mortgage' %></li>
      <li><%= t 'hub.may_not_work_if_you_live_overseas.student_loan' %></li>
      <li><%= t 'hub.may_not_work_if_you_live_overseas.payday_loan' %></li>
      <li><%= t 'hub.may_not_work_if_you_live_overseas.mail_order_account' %></li>
    </ul>

    <p><%= t 'hub.may_not_work_if_you_live_overseas.youll_also_need' %></p>

    <p><%= link_to t('hub.may_not_work_if_you_live_overseas.try_to_verify'), choose_a_certified_company_path %></p>

    <%= render partial: 'shared/other_ways', locals: { other_ways_text: @other_ways_text, other_ways_description: @other_ways_description } %>
  </div>
</div>