config/routes.rb
include LoaMatch
include AbTestConstraint

Rails.application.routes.draw do

  def add_routes(routes_name)
    instance_eval(File.read(Rails.root.join("config/#{routes_name}.rb")))
  end

  get "initiate-journey/:transaction_simple_id", to: "initiate_journey#index", as: :initiate_journey
  post "SAML2/SSO" => "authn_request#rp_request"
  post "SAML2/SSO/Response/POST" => "authn_response#idp_response"
  match "/404", to: "errors#page_not_found", via: :all

  if %w(test development).include?(Rails.env) || STUB_MODE
    mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
    get "test-saml" => "test_saml#index"
    get "/" => "test_saml#index"
    post "/" => "test_saml#index"
    post "test-rp", to: proc { |_| [200, {}, ["OK"]] }
    post "test-idp-request-endpoint" => "test_saml#idp_request"
    post "test-initiate-journey" => "test_saml#initiate_journey_session"
    get "test-session-expiry" => "test_saml#test_expiry"
    post "another-idp-endpoint" => "test_saml#idp_request"
    get "test-journey-hint" => "test_journey_hint_cookie#index", as: :test_journey_hint
    get "test-throttling-cookie/:idp" => "test_throttling_cookie#set_cookie"
    post "test-journey-hint" => "test_journey_hint_cookie#set_cookie", as: :test_journey_hint_submit
    get "test-single-idp-journey" => "test_single_idp_journey#index"
    get "analytics", to: "test_analytics#forward"
    post "csp-reporter", to: "test_csp_reporter#report"
  end

  constraints(format: /html/) do
    localized do
      add_routes :main_routes
    end
  end

  put "select-idp", to: "sign_in#select_idp_ajax", as: :select_idp_submit_ajax
  put "select-idp-for-registration", to: "choose_a_certified_company#select_idp_ajax", as: :select_idp_for_registration_ajax
  put "resume-with-idp", to: "paused_registration#resume_with_idp_ajax", as: :resume_with_idp_ajax
  get "service-status", to: "service_status#index", as: :service_status
  get "hint", to: "hint#ajax_request"
  get "successful-idp", to: "hint#last_successful_idp"
  get "/SAML2/metadata/sp", to: "metadata#service_providers", as: :service_provider_metadata
  get "/SAML2/metadata/idp", to: "metadata#identity_providers", as: :identity_provider_metadata
  if SINGLE_IDP_FEATURE
    get "get-available-services", to: "metadata#service_list"
    post "initiate-single-idp-journey", to: "single_idp_journey#redirect_from_idp"
    put "select-single-idp", to: "single_idp_journey#continue_ajax"
  end
  if PUBLISH_HUB_CONFIG_ENABLED
    get "hub/config/service-status", to: "publish_hub_config#service_status"
    match "hub/config/config/certificates/:path", to: "publish_hub_config#certificates", constraints: { path: /.*/ }, via: :get
  end
  get "/humans.txt", to: "static#humanstxt"
end

app/controllers/about_controller.rb
require "partials/viewable_idp_partial_controller"

class AboutController < ApplicationController
  include ViewableIdpPartialController

  layout "slides", only: :about_verify

  def about_verify
    @tailored_text = current_transaction.tailored_text
    @identity_providers = IDENTITY_PROVIDER_DISPLAY_DECORATOR.decorate_collection(identity_providers_available_for_registration)
    @next_page_path = is_journey_loa1? ? choose_a_certified_company_path : will_it_work_for_me_path
    if SIGN_UPS_ENABLED
      render :how_verify_works
    else
      redirect_to start_path
    end
  end

  def about_choosing_a_company
    @continue_path = is_journey_loa1? ? choose_a_certified_company_path : will_it_work_for_me_path
    if SIGN_UPS_ENABLED
      render :choosing_a_company
    else
      redirect_to start_path
    end
  end

  def about_documents
    @identity_providers = IDENTITY_PROVIDER_DISPLAY_DECORATOR.decorate_collection(identity_providers_available_for_registration)
    if SIGN_UPS_ENABLED
      render :documents
    else
      redirect_to start_path
    end
  end

  def prove_your_identity_another_way
    @other_ways_text = current_transaction.other_ways_text
    @service_name = current_transaction.name
    if SIGN_UPS_ENABLED
      render :prove_your_identity_another_way
    else
      redirect_to start_path
    end
  end
end

app/views/about/_logos_no.html.erb
<p><%= t 'hub.about_certified_companies.a_certified_company_will_verify_security' %></p>

app/views/about/_logos_privacy.html.erb
<p><%= t 'hub.about_certified_companies.a_certified_company_will_verify_security_start' %></p>

<p><%= t 'hub.about_certified_companies.ensure_privacy' %></p>

app/views/about/_logos_yes.html.erb
<p><%= t 'hub.about_certified_companies.a_certified_company_will_verify' %></p>

<ul class="list-companies">
  <% @identity_providers.each do |idp| %>
      <li>
        <%= image_tag idp.white_logo_path, alt: idp_tagline(idp) %>
      </li>
  <% end %>
</ul>

app/views/about/about_combined_LOA2.erb
<%= page_title 'hub.about.title' %>
<% content_for :feedback_source, 'ABOUT_PAGE' %>

<h1 class="govuk-heading-l"><%= t 'hub.about_what_is_verify.heading' %></h1>
<p><%= t 'hub.about_what_is_verify.content' %></p>
<%= raw @tailored_text %>

<h2 class="govuk-heading-m"><%= t 'hub.about_how_it_works.heading' %></h2>
<p><%= t 'hub.about_how_it_works.content' %></p>

<ul class="list-companies">
  <% @identity_providers.each do |idp| %>
    <li>
      <%= image_tag idp.white_logo_path, alt: t('common.logo', name: idp.display_name) %>
    </li>
  <% end %>
</ul>

<%= raw t 'hub.about_company.content_html' %>

<div class="actions">
  <%= button_link_to t('navigation.continue'), will_it_work_for_me_path, id: 'next-button', class: 'govuk-button' %>
</div>

app/views/about/certified_companies.html.erb
<%= page_title 'hub.about_certified_companies.title' %>
<% content_for :feedback_source, 'ABOUT_CERTIFIED_COMPANIES_PAGE' %>

<p><%= t 'hub.about_certified_companies.a_certified_company_will_verify' %></p>
<p><%=  t 'hub.about_certified_companies.dont_need_to_be_existing_customer' %></p>

<ul class="list-companies">
  <% @identity_providers.each do |idp| %>
      <li>
        <%= image_tag idp.white_logo_path, alt: idp_tagline(idp) %>
      </li>
  <% end %>
</ul>

<p><%= t 'hub.about_certified_companies.no_charge' %></p>

<div class="actions">
  <%= button_link_to t('navigation.next'), about_identity_accounts_path, id: 'next-button' %>
</div>

<details>
  <summary>
    <span class="summary"><%= t 'hub.about_certified_companies.summary' %></span>
  </summary>
  <div class="panel panel-border-narrow">
    <%= t 'hub.about_certified_companies.details_html' %>
  </div>
</details>

app/views/about/choosing_a_company.html.erb
<%= page_title 'hub.about.choosing_a_company.heading' %>
<% content_for :feedback_source, :ABOUT_CHOOSING_A_COMPANY_PAGE %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l"><%= t 'hub.about.choosing_a_company.heading' %></h1>
    <%= t 'hub.about.choosing_a_company.content_html' %>
    <div class="actions">
      <%= button_link_to t('navigation.continue'), @continue_path, id: 'next-button', class: 'govuk-button' %>
    </div>
  </div>
</div>

app/views/about/documents.html.erb
<% if @identity_providers.size > 1 %>
  <%= page_title 'hub.about.documents.multi_idp.heading' %>
<% else %>
  <%= page_title 'hub.about.documents.one_idp.heading', idp: @identity_providers.first.display_name %>
<% end %>

<% content_for :feedback_source, 'ABOUT_DOCUMENTS_PAGE' %>

<% if @identity_providers.size > 1 %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">

      <h1 class="govuk-heading-l"><%= t 'hub.about.documents.multi_idp.heading' %></h1>
      <p><%= t 'hub.about.documents.multi_idp.explanation' %></p>

      <p><%= t 'hub.about.documents.multi_idp.document_list.heading' %></p>
      <p><%= t 'hub.about.documents.multi_idp.document_list.list_html' %></p>

      <p><%= t 'hub.about.documents.multi_idp.further_explanation.doc_checking' %></p>
      <p><%= t 'hub.about.documents.multi_idp.further_explanation.requirements' %></p>
      <p><%= t 'hub.about.documents.multi_idp.further_explanation.come_back_later' %></p>

      <%= button_link_to t("navigation.continue"), choose_a_certified_company_path, id: 'next-button', class: 'govuk-button' %>
      <p class="govuk-!-margin-top-4"><%= t('hub.about.documents.prove_identity_another_way.text_html',
                                            link_text: link_to(t('hub.about.documents.prove_identity_another_way.link_text'), prove_your_identity_another_way_path, class: "govuk-link")
                                          ) %>
      </p>
    </div>
  </div>
<% else %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">

      <h1 class="govuk-heading-l"><%= t 'hub.about.documents.one_idp.heading', idp: @identity_providers.first.display_name %></h1>

      <%= raw t 'hub.about.documents.one_idp.content_html', idp: @identity_providers.first.display_name %>
      <%= form_for(@identity_providers.first, url: choose_a_certified_company_submit_path, html: { class: 'js-idp-form', id: nil }) do |f| %>
        <%= hidden_field_tag 'entity_id', @identity_providers.first.entity_id, id: nil, class: 'js-entity-id' %>
        <%= f.button t("hub.about.documents.one_idp.continue_btn", idp: @identity_providers.first.display_name ),
                     class: "govuk-button",
                     name: @identity_providers.first.simple_id,
                     id: nil,
                     type: 'submit',
                     value: @identity_providers.first.display_name %>
      <% end %>
      <div class="idp-choice govuk-grid-row" style="margin-top: 1em; min-height: 0; border: none">
        <div class="govuk-width-container">
          <div class="govuk-grid-column-one-third company-logo"><%= image_tag @identity_providers.first.logo_path, height: '60%', width: '60%', alt: t('common.logo', name: @identity_providers.first.display_name) %></div>
          <div class="govuk-grid-column-two-third"><p class="govuk-body-s"><%= link_to t('hub.about.documents.one_idp.more_link', idp: @identity_providers.first.display_name), choose_a_certified_company_about_path(@identity_providers.first.simple_id) %></p></div>
        </div>
      </div>
      <p class="govuk-!-margin-top-4"><%= t('hub.about.documents.prove_identity_another_way.text_html',
                                            link_text: link_to(t('hub.about.documents.prove_identity_another_way.link_text'), prove_your_identity_another_way_path, class: "govuk-link")
                                          ) %>
      </p>
    </div>
  </div>
<% end %>

app/views/about/how_verify_works.html.erb
<%= page_title 'hub.about.verify.what_it_is.heading' %>
<% content_for :feedback_source, 'ABOUT_VERIFY_PAGE' %>

<h1 class="govuk-heading-l"><%= t 'hub.about.verify.what_it_is.heading' %></h1>
<p><%= t 'hub.about.verify.what_it_is.content' %></p>
<%= raw @tailored_text %>

<h2 class="govuk-heading-m"><%= t 'hub.about.verify.how_it_works.heading' %></h2>
<% if @identity_providers.size > 1 %>
  <p><%= t 'hub.about.verify.how_it_works.content' %></p>

  <ul class="list-companies">
    <% @identity_providers.each do |idp| %>
      <li>
        <%= image_tag idp.white_logo_path, alt: t('common.logo', name: idp.display_name) %>
      </li>
    <% end %>
  </ul>

  <%= raw t 'hub.about.verify.company.content_html' %>
<% else %>
  <%= raw t 'hub.about.verify.one_idp.content_html', provider_name: @identity_providers.first.display_name %>
<% end %>
<div class="actions">
  <%= button_link_to t("navigation.continue"), @next_page_path, id: 'next-button', class: 'govuk-button' %>
</div>

app/views/about/identity_accounts.html.erb
<%= page_title 'hub.about_identity_accounts.title' %>
<% content_for :feedback_source, 'ABOUT_IDENTITY_ACCOUNTS_PAGE' %>

<%= t 'hub.about_identity_accounts.content_html' %>

<div class="actions">
  <%= button_link_to t('hub.about_identity_accounts.navigation.start_now'), about_choosing_a_company_path, id: 'next-button' %>
</div>

<details>
  <summary>
    <span class="summary"><%= t 'hub.about_identity_accounts.summary' %></span>
  </summary>
  <div class="panel panel-border-narrow">
    <p><%= t 'hub.about_identity_accounts.details' %></p>
    <ul class="list-bullet list">
      <% transactions_list.name_homepage.each do |transaction| -%>
          <li><%= transaction.name %></li>
      <% end %>
    </ul>
  </div>
</details>

app/views/about/index.html.erb
<%= page_title 'hub.about.title' %>
<% content_for :feedback_source, 'ABOUT_PAGE' %>

<p><%= t 'hub.about.verify_is_a_service' %></p>
<%= @tailored_text.html_safe %>

<div class="actions">
  <%= button_link_to t('navigation.next'), about_certified_companies_path, id: 'next-button' %>
</div>

app/views/about/prove_your_identity_another_way.html.erb
<%= page_title 'hub.about.prove_your_identity_another_way.heading' %>
<% content_for :feedback_source, :PROVE_YOUR_IDENTITY_ANOTHER_WAY_PAGE %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <h1 class="govuk-heading-l"><%= t("hub.about.prove_your_identity_another_way.heading") %></h1>
    <p class="govuk-body"><%= t("hub.about.prove_your_identity_another_way.sub_heading", service_name: @service_name) %></p>
      <div class="other-ways-to-complete-transaction">
        <%= raw @other_ways_text %>
      </div>
  </div>
</div>